export enum ConversationState {
    NONE = 'NONE',

       // Register
    REGISTER_WAITING_FIRST_NAME = 'REGISTER_WAITING_FIRST_NAME',
    REGISTER_WAITING_LAST_NAME = 'REGISTER_WAITING_LAST_NAME',

    // Expense
    EXPENSE_WAITING_TITLE = 'EXPENSE_WAITING_TITLE',
    EXPENSE_WAITING_AMOUNT = 'EXPENSE_WAITING_AMOUNT',
    EXPENSE_WAITING_CATEGORY = 'EXPENSE_WAITING_CATEGORY',
    EXPENSE_WAITING_NOTE ='EXPENSE_WAITING_NOTE',

    UPDATE_EXPENSE_WAITING_ID = 'UPDATE_EXPENSE_WAITING_ID',
    UPDATE_EXPENSE_WAITING_AMOUNT = 'UPDATE_EXPENSE_WAITING_AMOUNT',
    UPDATE_EXPENSE_WAITING_CATEGORY = 'UPDATE_EXPENSE_WAITING_CATEGORY',
    UPDATE_EXPENSE_WAITING_NOTE = 'UPDATE_EXPENSE_WAITING_NOTE',
    DELETE_EXPENSE_WAITING_ID = 'DELETE_EXPENSE_WAITING_ID',
    RESTORE_EXPENSE_WAITING_ID = 'RESTORE_EXPENSE_WAITING_ID' ,
    HARD_DELETE_EXPENSE_WAITING_ID = 'HARD_DELETE_EXPENSE_WAITING_ID' ,


    // Category
    ADD_CATEGORY_WAITING_NAME= 'ADD_CATEGORY_WAITING_NAME',
    UPDATE_CATEGORY_WAITING_ID = 'UPDATE_CATEGORY_WAITING_ID',
    UPDATE_CATEGORY_WAITING_NAME = 'UPDATE_CATEGORY_WAITING_NAME',
    DELETE_CATEGORY_WAITING_ID = 'DELETE_CATEGORY_WAITING_ID',
    RESTORE_CATEGORY_WAITING_ID = 'RESTORE_CATEGORY_WAITING_ID',
    HARD_DELETE_CATEGORY_WAITING_ID = 'HARD_DELETE_CATEGORY_WAITING_ID',


    // Ai 

    SCAN_RECEIPT_WAITING_IMAGE = 'SCAN_RECEIPT_WAITING_IMAGE',
    
  SCAN_RECEIPT_WAITING_CONFIRMATION = 'SCAN_RECEIPT_WAITING_CONFIRMATION',



}